### ISSUE TITLE
Not working on latest version of nova

### ISSUE THREAD

**Issue by Tim-Frensch** [optimistdigital/nova-color-field#4] opened 2021-09-01 09:40 UTC
On the latest version of nova the field doesn't seem to work properly.
I tried different types, but all seem to give the same errors:

It only affects the adding of a new color, the detail field and edit field work fine.
For now the workaround seems to just give the field a default value:

`            Color::make('Color')->default(function () { 
                return '#fff';
            }),`

`TypeError: Cannot read property 'h' of undefined`
`TypeError: Cannot read property 'hex' of undefined`

Nova 3.29.0
PHP 8

**Comment by Tarpsvo** [comment] 2021-09-03 12:15
Hi! I think I found the cause and it should be fixed in version 1.1.1. Thanks!

**Closed by Tarpsvo** 2021-09-03 12:15 UTC
